name = Sitewide
description = A sitewide one-column layout
template = sitewide-layout
preview = preview.png

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/sitewide/sitewide.layout.css
